# Generated by Django 4.2.7 on 2025-08-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_moto_motos_delete_auto_delete_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
